import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*export function Layout({ children }) {
  return (
    <div className="font-sans antialiased text-gray-800">
      <header className="bg-gray-800 text-white py-4 text-center">
        <nav>
          <a href="index.html" className="mx-2 hover:text-gray-300">
            Home
          </a>
          <a href="blog.html" className="mx-2 hover:text-gray-300">
            Blog
          </a>
        </nav>
      </header>

      <main>{children}</main>

      <footer className="bg-gray-800 text-white py-4 text-center">
        <p>© 2024 My Portfolio</p>
      </footer>
    </div>
  );
}*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
